const state = {
  searchUser: '',
  searchButtonConfirmLoading: false,
  searchButtonResetLoading: false,
  userId: '',
  userName: '',
  userSex: '',
  userPhone: '',
  userMenus: [],
  userMenuLoading: false,
  userCommunities: [],
  userCommunityLoading: false,
  modalStatusButtonLoading: false,
  tableData: [],
  tableLoading: false,
  tableTotals: 0,
  tableCurrent: 1,
  tablePageSize: 1,
  communityId: '',
  navLeftLoading: false,
  pathnameChange: true,
  pathnameCurrent: '',
  permissions: [],
  permissionsCurrent: 5,
  menus: [],
  menusCurrent: '10',
  menusSubCurrent: 'home',
}

export default state

